@guitarId={{createGuitar.response.body.id}}
@authToken={{login.response.body.token}}
###
## Получить токен для теста запросов в файле
# @name login
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@test.ru",
  "password": "admin123"
}
###

# Товары
## Получить список товаров (5.4)
### Все параметры:
### limit=7
### page=1
### sortBy=createdDate / price
### sortDirection=asc / desc
### type=ukulele / ukulele,electric
### stringsAmount=4 /4,6
GET http://localhost:4000/guitars?stringsAmount=4 HTTP/1.1
Content-Type: application/json

###

## Получить количество страниц товаров
GET http://localhost:4000/guitars/show-pages HTTP/1.1
Content-Type: application/json

###


## Создание нового товара (5.1)
# @name createGuitar
POST http://localhost:4000/guitars HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "СURT Z30 Plus",
    "description": "Гитара подходит как для старта обучения, так и для домашних занятий или использования в полевых условиях, например, в походах или для проведения уличных выступлений. Доступная стоимость, качество и надежная конструкция, а также приятный внешний вид, который сделает вас звездой вечеринки.",
    "createdDate": "2023-09-17T13:33:53.580Z",
    "type": "electric",
    "vendor": "SO754565",
    "price": 39319,
    "stringsAmount": 6
  }

###


## Показать детальную информацию по предложению (5.5)
GET http://localhost:4000/guitars/{{guitarId}} HTTP/1.1
Authorization: Bearer {{authToken}}
###

## Редактировать товар (5.2)
PATCH  http://localhost:4000/guitars/{{guitarId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "SZT 102 Test",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tincidunt augue felis, in ultrices quam pulvinar a. Vivamus bibendum justo id dapibus lacinia. Aenean in volutpat sapien. Nam commodo velit pharetra diam euismod, a semper tortor pulvinar. Nulla vulputate mauris id tempus pharetra"
  }

###

## Удалить товар (5.3)
DELETE http://localhost:4000/guitars/{{guitarId}} HTTP/1.1
Authorization: Bearer {{authToken}}
###

## Загрузить фото товара

POST http://localhost:4000/guitars/{{guitarId}}/photo HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{authToken}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="catalog-product-0.png"
Content-Type: image/jpeg

< ../../../../static/catalog-product-0.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
